var annotated_dup =
[
    [ "Audio", "namespace_audio.html", [
      [ "AudioSampleFifoQueue", "struct_audio_1_1_audio_sample_fifo_queue.html", "struct_audio_1_1_audio_sample_fifo_queue" ],
      [ "AudioSampleFifoQueueVector", "struct_audio_1_1_audio_sample_fifo_queue_vector.html", "struct_audio_1_1_audio_sample_fifo_queue_vector" ],
      [ "AudioSampleList", "struct_audio_1_1_audio_sample_list.html", "struct_audio_1_1_audio_sample_list" ],
      [ "AudioSampleListVector", "struct_audio_1_1_audio_sample_list_vector.html", "struct_audio_1_1_audio_sample_list_vector" ],
      [ "WaveFile", "struct_audio_1_1_wave_file.html", "struct_audio_1_1_wave_file" ]
    ] ],
    [ "BaseModules", "namespace_base_modules.html", [
      [ "_LoggingBufferEntry", "struct_base_modules_1_1___logging_buffer_entry.html", "struct_base_modules_1_1___logging_buffer_entry" ],
      [ "_LoggingTime", "class_base_modules_1_1___logging_time.html", "class_base_modules_1_1___logging_time" ],
      [ "CommandLineArgument", "struct_base_modules_1_1_command_line_argument.html", "struct_base_modules_1_1_command_line_argument" ],
      [ "CommandLineArgumentHandler", "struct_base_modules_1_1_command_line_argument_handler.html", "struct_base_modules_1_1_command_line_argument_handler" ],
      [ "CommandLineArgumentList", "struct_base_modules_1_1_command_line_argument_list.html", null ],
      [ "Environment", "struct_base_modules_1_1_environment.html", "struct_base_modules_1_1_environment" ],
      [ "File", "struct_base_modules_1_1_file.html", "struct_base_modules_1_1_file" ],
      [ "Logging", "struct_base_modules_1_1_logging.html", "struct_base_modules_1_1_logging" ],
      [ "OperatingSystem", "struct_base_modules_1_1_operating_system.html", "struct_base_modules_1_1_operating_system" ],
      [ "StringUtil", "struct_base_modules_1_1_string_util.html", "struct_base_modules_1_1_string_util" ]
    ] ],
    [ "BaseTypes", "namespace_base_types.html", [
      [ "Containers", "namespace_base_types_1_1_containers.html", [
        [ "ByteList", "struct_base_types_1_1_containers_1_1_byte_list.html", "struct_base_types_1_1_containers_1_1_byte_list" ],
        [ "Dictionary", "struct_base_types_1_1_containers_1_1_dictionary.html", "struct_base_types_1_1_containers_1_1_dictionary" ],
        [ "IntegerList", "struct_base_types_1_1_containers_1_1_integer_list.html", "struct_base_types_1_1_containers_1_1_integer_list" ],
        [ "NaturalList", "struct_base_types_1_1_containers_1_1_natural_list.html", "struct_base_types_1_1_containers_1_1_natural_list" ],
        [ "NaturalSet", "struct_base_types_1_1_containers_1_1_natural_set.html", null ],
        [ "RealList", "struct_base_types_1_1_containers_1_1_real_list.html", "struct_base_types_1_1_containers_1_1_real_list" ],
        [ "StringList", "struct_base_types_1_1_containers_1_1_string_list.html", "struct_base_types_1_1_containers_1_1_string_list" ]
      ] ],
      [ "Primitives", "namespace_base_types_1_1_primitives.html", [
        [ "Boolean", "struct_base_types_1_1_primitives_1_1_boolean.html", "struct_base_types_1_1_primitives_1_1_boolean" ],
        [ "Byte", "struct_base_types_1_1_primitives_1_1_byte.html", "struct_base_types_1_1_primitives_1_1_byte" ],
        [ "Character", "struct_base_types_1_1_primitives_1_1_character.html", "struct_base_types_1_1_primitives_1_1_character" ],
        [ "Integer", "struct_base_types_1_1_primitives_1_1_integer.html", "struct_base_types_1_1_primitives_1_1_integer" ],
        [ "Natural", "struct_base_types_1_1_primitives_1_1_natural.html", "struct_base_types_1_1_primitives_1_1_natural" ],
        [ "Percentage", "struct_base_types_1_1_primitives_1_1_percentage.html", "struct_base_types_1_1_primitives_1_1_percentage" ],
        [ "Radians", "struct_base_types_1_1_primitives_1_1_radians.html", "struct_base_types_1_1_primitives_1_1_radians" ],
        [ "Real", "struct_base_types_1_1_primitives_1_1_real.html", "struct_base_types_1_1_primitives_1_1_real" ]
      ] ]
    ] ],
    [ "Libraries", "namespace_libraries.html", [
      [ "FluidSynth", "namespace_libraries_1_1_fluid_synth.html", [
        [ "_SynthesizerDescriptor", "struct_libraries_1_1_fluid_synth_1_1___synthesizer_descriptor.html", "struct_libraries_1_1_fluid_synth_1_1___synthesizer_descriptor" ],
        [ "FluidSynth", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth.html", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth" ],
        [ "FluidSynthSettings", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_settings.html", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_settings" ],
        [ "FluidSynthSoundFont", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_sound_font.html", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_sound_font" ],
        [ "FluidSynthSynthesizer", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_synthesizer.html", "struct_libraries_1_1_fluid_synth_1_1_fluid_synth_synthesizer" ]
      ] ],
      [ "DynamicLibrary", "struct_libraries_1_1_dynamic_library.html", "struct_libraries_1_1_dynamic_library" ]
    ] ],
    [ "Main", "namespace_main.html", [
      [ "FluidSynthFileConverter", "namespace_main_1_1_fluid_synth_file_converter.html", [
        [ "ConverterProgram", "struct_main_1_1_fluid_synth_file_converter_1_1_converter_program.html", "struct_main_1_1_fluid_synth_file_converter_1_1_converter_program" ]
      ] ],
      [ "FluidSynthPlugin", "namespace_main_1_1_fluid_synth_plugin.html", [
        [ "_EditorDescriptor", "struct_main_1_1_fluid_synth_plugin_1_1___editor_descriptor.html", "struct_main_1_1_fluid_synth_plugin_1_1___editor_descriptor" ],
        [ "_EventProcessorDescriptor", "struct_main_1_1_fluid_synth_plugin_1_1___event_processor_descriptor.html", "struct_main_1_1_fluid_synth_plugin_1_1___event_processor_descriptor" ],
        [ "_PresetSelectionComponent", "struct_main_1_1_fluid_synth_plugin_1_1___preset_selection_component.html", "struct_main_1_1_fluid_synth_plugin_1_1___preset_selection_component" ],
        [ "_RingBuffer", "struct_main_1_1_fluid_synth_plugin_1_1___ring_buffer.html", "struct_main_1_1_fluid_synth_plugin_1_1___ring_buffer" ],
        [ "_StringListBoxModel", "struct_main_1_1_fluid_synth_plugin_1_1___string_list_box_model.html", "struct_main_1_1_fluid_synth_plugin_1_1___string_list_box_model" ],
        [ "_TextWidget", "struct_main_1_1_fluid_synth_plugin_1_1___text_widget.html", "struct_main_1_1_fluid_synth_plugin_1_1___text_widget" ],
        [ "_WidgetListener", "struct_main_1_1_fluid_synth_plugin_1_1___widget_listener.html", "struct_main_1_1_fluid_synth_plugin_1_1___widget_listener" ],
        [ "FluidSynthPlugin_Editor", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___editor.html", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___editor" ],
        [ "FluidSynthPlugin_EditorSupport", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___editor_support.html", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___editor_support" ],
        [ "FluidSynthPlugin_EventProcessor", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___event_processor.html", "struct_main_1_1_fluid_synth_plugin_1_1_fluid_synth_plugin___event_processor" ]
      ] ],
      [ "BuildInformation", "struct_main_1_1_build_information.html", "struct_main_1_1_build_information" ]
    ] ],
    [ "MIDI", "namespace_m_i_d_i.html", [
      [ "_MidiEventConverterDescriptor", "struct_m_i_d_i_1_1___midi_event_converter_descriptor.html", "struct_m_i_d_i_1_1___midi_event_converter_descriptor" ],
      [ "_MidiEventDescriptor", "struct_m_i_d_i_1_1___midi_event_descriptor.html", "struct_m_i_d_i_1_1___midi_event_descriptor" ],
      [ "MidiEvent", "struct_m_i_d_i_1_1_midi_event.html", "struct_m_i_d_i_1_1_midi_event" ],
      [ "MidiEventConverter", "struct_m_i_d_i_1_1_midi_event_converter.html", "struct_m_i_d_i_1_1_midi_event_converter" ],
      [ "MidiEventKind", "struct_m_i_d_i_1_1_midi_event_kind.html", "struct_m_i_d_i_1_1_midi_event_kind" ],
      [ "MidiEventList", "struct_m_i_d_i_1_1_midi_event_list.html", "struct_m_i_d_i_1_1_midi_event_list" ],
      [ "MidiFile", "struct_m_i_d_i_1_1_midi_file.html", "struct_m_i_d_i_1_1_midi_file" ],
      [ "MidiMetaEventKind", "struct_m_i_d_i_1_1_midi_meta_event_kind.html", "struct_m_i_d_i_1_1_midi_meta_event_kind" ],
      [ "MidiPresetIdentification", "struct_m_i_d_i_1_1_midi_preset_identification.html", "struct_m_i_d_i_1_1_midi_preset_identification" ]
    ] ],
    [ "Windows", null, [
      [ "tagBITMAP", "struct_windows_1_1tag_b_i_t_m_a_p.html", null ],
      [ "tagBITMAPINFO", "struct_windows_1_1tag_b_i_t_m_a_p_i_n_f_o.html", null ],
      [ "tagBITMAPINFOHEADER", "struct_windows_1_1tag_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", null ],
      [ "tagDRAWTEXTPARAMS", "struct_windows_1_1tag_d_r_a_w_t_e_x_t_p_a_r_a_m_s.html", null ],
      [ "tagLOGFONTW", "struct_windows_1_1tag_l_o_g_f_o_n_t_w.html", null ],
      [ "tagMSG", "struct_windows_1_1tag_m_s_g.html", null ],
      [ "tagPAINTSTRUCT", "struct_windows_1_1tag_p_a_i_n_t_s_t_r_u_c_t.html", null ],
      [ "tagPOINT", "struct_windows_1_1tag_p_o_i_n_t.html", null ],
      [ "tagRECT", "struct_windows_1_1tag_r_e_c_t.html", null ],
      [ "tagRGBQUAD", "struct_windows_1_1tag_r_g_b_q_u_a_d.html", null ],
      [ "tagWNDCLASSEXW", "struct_windows_1_1tag_w_n_d_c_l_a_s_s_e_x_w.html", null ]
    ] ],
    [ "_EditorDescriptor", "struct___editor_descriptor.html", "struct___editor_descriptor" ],
    [ "_EventProcessorDescriptor", "struct___event_processor_descriptor.html", "struct___event_processor_descriptor" ],
    [ "_EventTime", "struct___event_time.html", "struct___event_time" ],
    [ "_LoggingBufferEntry", "struct___logging_buffer_entry.html", "struct___logging_buffer_entry" ],
    [ "_LoggingTime", "class___logging_time.html", "class___logging_time" ],
    [ "_MidiEventConverterDescriptor", "struct___midi_event_converter_descriptor.html", "struct___midi_event_converter_descriptor" ],
    [ "_MidiEventDescriptor", "struct___midi_event_descriptor.html", "struct___midi_event_descriptor" ],
    [ "_PresetSelectionComponent", "struct___preset_selection_component.html", "struct___preset_selection_component" ],
    [ "_RingBuffer", "struct___ring_buffer.html", "struct___ring_buffer" ],
    [ "_StringListBoxModel", "struct___string_list_box_model.html", "struct___string_list_box_model" ],
    [ "_TextWidget", "struct___text_widget.html", "struct___text_widget" ],
    [ "_WidgetListener", "struct___widget_listener.html", "struct___widget_listener" ],
    [ "AudioSampleFifoQueue", "struct_audio_sample_fifo_queue.html", "struct_audio_sample_fifo_queue" ],
    [ "AudioSampleFifoQueueVector", "struct_audio_sample_fifo_queue_vector.html", "struct_audio_sample_fifo_queue_vector" ],
    [ "AudioSampleList", "struct_audio_sample_list.html", "struct_audio_sample_list" ],
    [ "AudioSampleListVector", "struct_audio_sample_list_vector.html", "struct_audio_sample_list_vector" ],
    [ "Boolean", "struct_boolean.html", "struct_boolean" ],
    [ "BuildInformation", "struct_build_information.html", "struct_build_information" ],
    [ "Byte", "struct_byte.html", "struct_byte" ],
    [ "ByteList", "struct_byte_list.html", "struct_byte_list" ],
    [ "Character", "struct_character.html", "struct_character" ],
    [ "CommandLineArgument", "struct_command_line_argument.html", "struct_command_line_argument" ],
    [ "CommandLineArgumentHandler", "struct_command_line_argument_handler.html", "struct_command_line_argument_handler" ],
    [ "CommandLineArgumentList", "struct_command_line_argument_list.html", null ],
    [ "ConverterProgram", "struct_converter_program.html", "struct_converter_program" ],
    [ "Dictionary", "struct_dictionary.html", "struct_dictionary" ],
    [ "DynamicLibrary", "struct_dynamic_library.html", "struct_dynamic_library" ],
    [ "Environment", "struct_environment.html", "struct_environment" ],
    [ "File", "struct_file.html", "struct_file" ],
    [ "FluidSynth", "struct_fluid_synth.html", "struct_fluid_synth" ],
    [ "FluidSynthPlugin_Editor", "struct_fluid_synth_plugin___editor.html", "struct_fluid_synth_plugin___editor" ],
    [ "FluidSynthPlugin_EditorSupport", "struct_fluid_synth_plugin___editor_support.html", "struct_fluid_synth_plugin___editor_support" ],
    [ "FluidSynthPlugin_EventProcessor", "struct_fluid_synth_plugin___event_processor.html", "struct_fluid_synth_plugin___event_processor" ],
    [ "FluidSynthSettings", "struct_fluid_synth_settings.html", "struct_fluid_synth_settings" ],
    [ "FluidSynthSoundFont", "struct_fluid_synth_sound_font.html", "struct_fluid_synth_sound_font" ],
    [ "FluidSynthSynthesizer", "struct_fluid_synth_synthesizer.html", "struct_fluid_synth_synthesizer" ],
    [ "Integer", "struct_integer.html", "struct_integer" ],
    [ "IntegerList", "struct_integer_list.html", "struct_integer_list" ],
    [ "Logging", "struct_logging.html", "struct_logging" ],
    [ "MidiEvent", "struct_midi_event.html", "struct_midi_event" ],
    [ "MidiEventConverter", "struct_midi_event_converter.html", "struct_midi_event_converter" ],
    [ "MidiEventKind", "struct_midi_event_kind.html", "struct_midi_event_kind" ],
    [ "MidiEventList", "struct_midi_event_list.html", "struct_midi_event_list" ],
    [ "MidiFile", "struct_midi_file.html", "struct_midi_file" ],
    [ "MidiMetaEventKind", "struct_midi_meta_event_kind.html", "struct_midi_meta_event_kind" ],
    [ "MidiPresetIdentification", "struct_midi_preset_identification.html", "struct_midi_preset_identification" ],
    [ "Natural", "struct_natural.html", "struct_natural" ],
    [ "NaturalList", "struct_natural_list.html", "struct_natural_list" ],
    [ "NaturalSet", "struct_natural_set.html", null ],
    [ "OperatingSystem", "struct_operating_system.html", "struct_operating_system" ],
    [ "Percentage", "struct_percentage.html", "struct_percentage" ],
    [ "Real", "struct_real.html", "struct_real" ],
    [ "RealList", "struct_real_list.html", "struct_real_list" ],
    [ "StringList", "struct_string_list.html", "struct_string_list" ],
    [ "StringUtil", "struct_string_util.html", "struct_string_util" ],
    [ "WaveFile", "struct_wave_file.html", "struct_wave_file" ]
];